### ISSUE TITLE
lprint command issues

### ISSUE THREAD

**Issue by Stuart1066** [michaelrsweet/lprint#37]
I use Zebra label printers shared from Windows PCs which causes me some issues. Lprint running on a single board Linux computer looks like perfect solution to my sharing issues so I purchased a FriendlyARM NanoPi NEO-LTS 512MB to act as a print server. I installed the FriendlyCore image with Ubuntu Core 16.04.7 kernel 4.14.111 and fully upgraded and updated it before installing the lprint snap. I also installed the edge snap of cups to install version 2.4. I also installed libusb-1.0 and libpng16-16 so I think I have all the dependencies covered.

I have a couple of problems running lprint which I’m hoping you can help me with please, I’m running these as root.

1. When I run the command `lprint server -o server-name=ps1 -o server-port=80` I get the message “Ignored Avahi state 101.” and it I don’t get the command prompt back. The server is running and I can view the lprint Printers page from a browser. I was unsure of the avahi version so I tried installing an avahi snap taking it to version 0.8, after that I received the message “Ignored Avahi state 101.” instead.

2. I have a Zebra GK420D connected via USB and can see it when I `run lsusb` however when I run `lprint devices` I get the message “lprint: Unable to initialize USB access: Other error”. I did see the other issue regarding permissions but I’m running the command as root.

3. If I run ` ps ax | grep lprint` I can see that lprint appears to be running. If I then run `lprint shutdown` I get the message “lprint: Unable to shutdown server – Success” and lprint still appears to be running.

If you have any advice on what I should try next that would be greatly appreciated as I’ve exhausted my knowledge and the info I can find online. Thank you.

**Comment by michaelrsweet** [comment]
@Stuart1066 I think the latest code (which uses PAPPL) should fix these issues. If you can try building from source (you'll also need to build and install [PAPPL](https://www.msweet.org/pappl) before updating the building the current LPrint code) and report back, that would be very helpful.

FWIW, I have an old Pi Zero W setup with my three label printers (2 Zebra and 1 DYMO) and it seems to be working well for me.

**Comment by michaelrsweet** [comment]
@Stuart1066 OK, I've promoted the current snap build to beta - please try installing the update lprint 1.1 and let me know what happens.

**Comment by Stuart1066** [comment]
@michaelrsweet Thank you for the update, I will test it but unfortunately I won't get time before Christmas. We run an online retail business and our label printers are currently red hot! I should get an opportunity to try this once things quieten down. Thanks for your work on this and Happy Christmas.

**Comment by Stuart1066** [comment]
@michaelrsweet I've had time to retry this with your update and I'm sorry to report I still have the USB problem. As far as I can see everything else is working, I can start the server, use the lprint web interface and see my network printer in the list of devices but not the attached USB printer. I used a newer Ubuntu build to see if that made a difference.

I installed Friendly Core Ubuntu 20.04.3 LTS and then login as root to run:

```
apt update
apt upgrade
apt-get install build-essential libavahi-client-dev libcups2-dev \
        libcupsimage2-dev libgnutls28-dev libjpeg-dev libpam-dev libpng-dev \
        libusb-1.0-0-dev zlib1g-dev usbutils snapd cups
reboot

wget https://github.com/michaelrsweet/pappl/releases/download/v1.1.0/pappl-1.1.0.tar.gz
tar xvzf pappl-1.1.0.tar.gz
cd pappl-1.1.0
./configure
make
make install
reboot

snap install lprint --channel=latest/beta
reboot
```

When I run `lprint devices` I get
```
snmp://
lprint: Unable to initialize USB access: Other error
```
Running `sudo lsusb -v` and `ls -Rl /dev/bus/usb` appears to give normal results which are attached.
[output.txt](https://github.com/michaelrsweet/lprint/files/7795838/output.txt)

If there are other things you want me to try then please let me know.

**Comment by michaelrsweet** [comment]
@Stuart1066 Hmm, I'm trying some things from my new Pi Zero2 board and am getting the same errors. If you try building lprint from source and installing that (instead of using the snap) I think you'll have better results.

I need to fiddle some more with the snap stuff to see why USB isn't working... :/

**Comment by Stuart1066** [comment]
@michaelrsweet Thanks for the reply. I did install lprint from source onto my non-working installation and it was successful, lprint was able to access the USB printer without a problem. I then thought I would rebuild the os and application to ensure I had a reproducible working build. Unfortunately I haven't been able to get lprint working again. I install Friendly Core Ubuntu 20.04.3 LTS and then login as root
```
apt update
apt upgrade
apt-get install build-essential libavahi-client-dev libcups2-dev \
        libcupsimage2-dev libgnutls28-dev libjpeg-dev libpam-dev libpng-dev \
        libusb-1.0-0-dev zlib1g-dev usbutils snapd cups
reboot

wget https://github.com/michaelrsweet/pappl/releases/download/v1.1.0/pappl-1.1.0.tar.gz
tar xvzf pappl-1.1.0.tar.gz
cd pappl-1.1.0
./configure
make
make install
reboot

wget https://github.com/michaelrsweet/lprint/releases/download/v1.1.0/lprint-1.1.0.tar.gz
tar xvzf lprint-1.1.0.tar.gz
cd lprint-1.1.0
./configure
make
make install
reboot
```

I don't see any errors and the only warning is from the make of lprint.
```
root@NanoPi-NEO:~/lprint-1.1.0# make
Compiling lprint-common.c...
Compiling lprint-dymo.c...
Compiling lprint-epl2.c...
Compiling lprint-testpage.c...
Compiling lprint-zpl.c...
Compiling lprint.c...
lprint.c: In function ‘printer_cb’:
lprint.c:343:48: warning: ‘%d’ directive output may be truncated writing between 1 and 2 bytes into a region of size between 0 and 1023 [-Wformat-truncation=]
  343 |         snprintf(newname, sizeof(newname), "%s %d", name, i);
      |                                                ^~
lprint.c:343:44: note: directive argument in the range [2, 99]
  343 |         snprintf(newname, sizeof(newname), "%s %d", name, i);
      |                                            ^~~~~~~
In file included from /usr/include/stdio.h:867,
                 from /usr/local/include/pappl/base.h:20,
                 from /usr/local/include/pappl/device.h:17,
                 from /usr/local/include/pappl/pappl.h:17,
                 from lprint.h:19,
                 from lprint.c:14:
/usr/include/arm-linux-gnueabihf/bits/stdio2.h:67:10: note: ‘__builtin___snprintf_chk’ output between 3 and 1027 bytes into a destination of size 1024
   67 |   return __builtin___snprintf_chk (__s, __n, __USE_FORTIFY_LEVEL - 1,
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   68 |        __bos (__s), __fmt, __va_arg_pack ());
      |        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Linking lprint...

```
Running lprint I get the following error
```
root@NanoPi-NEO:~/lprint-1.1.0# lprint status
lprint: error while loading shared libraries: libpappl.so.1: cannot open shared object file: No such file or directory
```
I did also try installing lprint with snap before then building it from source (as that was what had happened on my previous working build) but unfortunately that didn't get things working, I get the same error.

I don't normally build things from source so if I'm doing something wrong then please let me know. If you need any extra information or you want me to try something then I'm happy to help.

**Comment by Stuart1066** [comment]
@michaelrsweet I found I can eliminate the error with libpappl.so.1 by using the `ldconfig` command.  Once this is done lprint is able to run and can see the USB printer
```
root@NanoPi-NEO:~# lprint devices
snmp://
usb://Zebra%20Technologies/ZTC%20GK420d?serial=28J213700376

```
The small issue I noticed with the screen output was that the spaces in the name are encoded as %20.

I was able to start the server and use the web interface to setup the Zebra printer and print a test page. The printer did not appear to be advertised on the network until the next time lprint server was started.
